language: python
python:
  - "3.9"

services:
  - postgresql

branches:
  only:
    - main

jobs:
  include:
  - name: "Python on Windows"
    os: windows
    language: shell

script: python run -m unittest test_flask.py

notifications:
  email:
    recipients:
      - iryna.yarka@gmail.com
