language: python
python:
  - "3.9"

services:
  - postgresql

branches:
  only:
    - lab-6

script: python3 app.py || python app.py

notifications:
  email:
    recipients:
      - iryna.yarka@gmail.com
