language: python
python:
  - "3.9"

services:
  - postgresql

branches:
  only:
    - lab-6

jobs:
  include:
  - name: "Python on Windows"
      os: windows
      language: shell

script: unittest

notifications:xqxq
  email:
    recipients:
      - iryna.yarka@gmail.com