"""empty message

Revision ID: 7277aaeba64a
Revises: 7551ca4ed77b
Create Date: 2020-12-09 00:34:17.523242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7277aaeba64a'
down_revision = '7551ca4ed77b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Car', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Car', 'price')
    # ### end Alembic commands ###
